--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/NickUI
build-by-default: true
branches:
- PM4
projects:
  NickUI:
    path: ""
    icon: icon.png
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.0.0
      - src: CortexPE/Commando/Commando
        version:  ^3.0.0
        branch: PM4
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.0.1
    lint:
      phpstan: false
...
