#   _   _   _          _      _   _   ___ 
#  | \ | | (_)   ___  | | __ | | | | |_ _|
#  |  \| | | |  / __| | |/ / | | | |  | | 
#  | |\  | | | | (__  |   <  | |_| |  | | 
#  |_| \_| |_|  \___| |_|\_\  \___/  |___|
#         by fernanACM
# Here you can make the necessary adjustments for the NickUI

# =======(SETTINGS)=======
Settings:
  # Put the maximum characters for the nicks
  characters: 15
  # Add random nicknames with this example:
  # Random-nicks:
  #   - Friend
  #   - ACM
  #   - Cars
  random-nicks:
    - "ACM"
    - "Jonatan"
    - "Mrc"
    - "AbelGod"
    - "Naruto"
    - "Pro"
    - "Sipe"
    - "New_122"
